default:
  app:
    namespace: argocd
    project: apps
    autoSync: true

apps:
  apache:
    enabled: true
    #namespace: null
    project: apps
    destination:
      namespace: my-apps-1
    autoSync: true  

  helm-nginx:
    enabled: true
    #namespace: null
    project: apps
    destination:
      namespace: my-apps-2  
    autoSync: true    

  helm-guestbook:
    enabled: true
    #namespace: null
    project: apps
    destination:
      namespace: my-apps-3  
    autoSync: true    



