apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aaa
  namespace: argocd
  
spec:
  source:
    path: App-of-Apps
    repoURL: 'https://github.com/jenana-devops/argocd-helm-app-of-apps.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml

  destination:
    namespace: 'default'
    server: 'https://kubernetes.default.svc'

  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true