apps:
  apache:
    enabled: true
    project: null
    autoSync: true

  helm-nginx:
    enabled: true
    project: null
    autoSync: true
 
  helm-guestbook:
    enabled: true
    project: null
    autoSync: true

  kustomize-guestbook:
    enabled: false
    project: null
    autoSync: true  

  helm-dependency:
    enabled: false
    project: null
    autoSync: true     


default:
  app:
    namespace: argocd
    project: apps
    targetRevision: v3-main-child-helm
    autoSync: false
