{{- range $app := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.appname }}
  namespace: argocd
spec:
  project: {{ $app.projectname }}

  source:
    path: {{ $app.appname }}
    repoURL: "https://github.com/jenana-devops/argocd-helm-app-of-apps.git"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml

  destination:
    namespace: {{ $app.destination.namespace }}
    server: 'https://kubernetes.default.svc'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---      
{{- end }}