{{- range $key, $val := .Values.apps }}
{{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: {{ $val.namespace | default $.Values.default.app.namespace }}
spec:
  project: {{ $val.project | default $.Values.default.app.project }}

  source:
    path: {{ $key }}
    repoURL: {{ $val.source.repoURL | default $.Values.default.app.source.repoURL }}
    targetRevision: {{ $val.source.targetRevision | default $.Values.default.app.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        #- {{ $val.source.helm.valueFiles }}
  
  destination:
    namespace: {{ $val.destination.namespace | default $.Values.default.app.destination.namespace }}
    server: {{ $val.destination.server | default $.Values.default.app.destination.server }}

  {{- if $val.autoSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
  {{- end }}    
---      
{{- end }}
{{- end }}