{{- range $key, $val := .Values.apps }}
{{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: {{ $val.namespace | default $.Values.default.app.namespace }}
spec:
  project: {{ $val.project | default $.Values.default.app.project }}

  source:
    path: {{ $key }}
    # {{ $val.source.repoURL | default $.Values.default.app.source.repoURL }} error
    # default 에 app.a.b 로 넘어가면 에러가 뜬다 app.a 까지 가능
    repoURL: "https://github.com/jenana-devops/argocd-helm-app-of-apps.git"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml

  destination:
    namespace: {{ $val.destination.namespace }}
    server: "https://kubernetes.default.svc"

  {{- if $val.autoSync | default $.Values.default.app.autoSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  {{- end }}    
---      
{{- end }}
{{- end }}